from pathlib import Path
from tempfile import TemporaryDirectory
import unittest

from ariad_fabrication.slicing import GCodePreflightReport, GCodeSummary, ProfileBundle
from ariad_fabrication.slicing.prusaslicer import ModelInfo, parse_slicer_warnings


ROOT = Path(__file__).resolve().parents[1]
PROFILE_ROOT = ROOT / "profiles" / "v1"


def _bundle() -> ProfileBundle:
    return ProfileBundle.from_paths(
        printer_path=PROFILE_ROOT / "printers" / "generic_open_fdm_220.json",
        material_path=PROFILE_ROOT / "materials" / "generic_pla_175.json",
        process_path=PROFILE_ROOT / "processes" / "standard_020_no_support.json",
        orientation_path=PROFILE_ROOT / "orientations" / "upright_source_z_centered.json",
        slicer_config_path=PROFILE_ROOT
        / "prusaslicer"
        / "generic_open_fdm_220__generic_pla__standard_020_no_support.ini",
    )


def _gcode(*, extra_command: str = "") -> str:
    return f"""; generated by PrusaSlicer 2.9.6 on 2026-07-16 at 00:00:00 UTC
M190 S60
M104 S210
G28
M109 S210
G21
G90
M82
;LAYER_CHANGE
;Z:0.2
;TYPE:External perimeter
G1 Z0.2 F1200
G1 X80 Y90 E0.1
G1 X140 Y130 E0.2
{extra_command}
M104 S0
M140 S0
; filament used [mm] = 1000.00
; filament used [cm3] = 2.41
; total filament used [g] = 2.99
; estimated printing time (normal mode) = 1h 1m 1s
; layer_height = 0.2
; support_material = 0
"""


class RealGCodePreflightTests(unittest.TestCase):
    def test_parser_and_preflight_accept_profile_specific_disconnected_gcode(self):
        with TemporaryDirectory() as temporary:
            path = Path(temporary) / "fixture.gcode"
            path.write_text(_gcode(), encoding="utf-8")
            summary = GCodeSummary.parse(path)
            report = GCodePreflightReport.evaluate(summary, _bundle())

        self.assertEqual(summary.layer_count, 1)
        self.assertEqual(summary.estimated_seconds, 3661)
        self.assertEqual(summary.filament_mass_g, 2.99)
        self.assertEqual(summary.motion_bounds_mm["max_x"], 140.0)
        self.assertTrue(report.passed)

    def test_preflight_fails_for_a_forbidden_persistent_firmware_command(self):
        with TemporaryDirectory() as temporary:
            path = Path(temporary) / "forbidden.gcode"
            path.write_text(_gcode(extra_command="M500"), encoding="utf-8")
            summary = GCodeSummary.parse(path)
            report = GCodePreflightReport.evaluate(summary, _bundle())

        self.assertEqual(summary.forbidden_commands, ("M500",))
        self.assertFalse(report.passed)
        self.assertIn("forbidden_commands", report.errors)

    def test_preflight_fails_for_unsupported_temperature_and_multiple_tools(self):
        with TemporaryDirectory() as temporary:
            path = Path(temporary) / "unsafe.gcode"
            path.write_text(
                _gcode(extra_command="M104 S300\nM109 S300\nT1"),
                encoding="utf-8",
            )
            report = GCodePreflightReport.evaluate(GCodeSummary.parse(path), _bundle())

        self.assertFalse(report.passed)
        self.assertIn("nozzle_temperature", report.errors)
        self.assertIn("single_tool", report.errors)

    def test_malformed_gcode_fails_closed_without_layers_or_modes(self):
        with TemporaryDirectory() as temporary:
            path = Path(temporary) / "malformed.gcode"
            path.write_text("this is not machine code\n", encoding="utf-8")
            report = GCodePreflightReport.evaluate(GCodeSummary.parse(path), _bundle())

        self.assertFalse(report.passed)
        self.assertIn("has_layers", report.errors)
        self.assertIn("millimetre_units", report.errors)
        self.assertIn("extrusion_mode", report.errors)

    def test_model_info_and_slicer_warning_parsers_preserve_repairs_and_findings(self):
        info = ModelInfo.parse(
            """[3DBenchy.stl]
size_x = 60.001
size_y = 31.004
size_z = 48
min_x = -29.176
min_y = -15.502
min_z = 0
max_x = 30.825
max_y = 15.502
max_z = 48
number_of_facets = 225154
manifold = yes
degenerate_facets = 552
facets_removed = 552
number_of_parts = 1
volume = 15550.38
"""
        )
        warnings = parse_slicer_warnings(
            """print warning: Detected print stability issues:

3DBenchy.stl
Low bed adhesion

Consider enabling supports.
69 => next stage
"""
        )

        self.assertTrue(info.manifold)
        self.assertEqual(info.facets_removed, 552)
        self.assertEqual(warnings, ("Low bed adhesion",))


if __name__ == "__main__":
    unittest.main()
