"""Parse real slicer G-code and apply profile-specific disconnected preflight."""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
import hashlib
from pathlib import Path
import re
from typing import Any

from .profiles import ProfileBundle


_TIME = re.compile(
    r"estimated printing time \(normal mode\) =\s*(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?",
    re.IGNORECASE,
)
_FILAMENT = re.compile(r"filament used \[(mm|cm3)\] =\s*([0-9.]+)", re.IGNORECASE)
_FILAMENT_G = re.compile(r"total filament used \[g\] =\s*([0-9.]+)", re.IGNORECASE)
_TOKEN = re.compile(r"^([A-Za-z])([-+]?(?:\d+(?:\.\d*)?|\.\d+))$")
_COMMAND = re.compile(r"^([GMT])(\d+(?:\.\d+)?)$", re.IGNORECASE)


FORBIDDEN_COMMANDS = frozenset(
    {
        "M0",
        "M1",
        "M25",
        "M112",
        "M226",
        "M303",
        "M500",
        "M501",
        "M502",
        "M600",
        "M997",
        "M999",
    }
)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _seconds(match: re.Match[str]) -> int:
    days, hours, minutes, seconds = (int(item or 0) for item in match.groups())
    return days * 86400 + hours * 3600 + minutes * 60 + seconds


@dataclass(frozen=True)
class GCodeSummary:
    path: Path
    slicer_version: str
    generated_at: str | None
    layer_count: int
    layer_z_min_mm: float
    layer_z_max_mm: float
    estimated_seconds: int
    filament_length_mm: float
    filament_volume_cm3: float
    filament_mass_g: float
    motion_bounds_mm: dict[str, float]
    nozzle_temperatures_c: tuple[float, ...]
    bed_temperatures_c: tuple[float, ...]
    units_mm: bool
    absolute_xyz: bool
    extrusion_mode: str | None
    tools: tuple[int, ...]
    feature_counts: dict[str, int]
    command_counts: dict[str, int]
    forbidden_commands: tuple[str, ...]
    embedded_config: dict[str, str]

    @classmethod
    def parse(cls, path: Path) -> "GCodeSummary":
        path = path.resolve()
        text = path.read_text(encoding="utf-8", errors="replace")
        lines = text.splitlines()
        version = "unknown"
        generated_at: str | None = None
        if lines:
            header = re.match(
                r"; generated by PrusaSlicer ([^ ]+) on (.+)$",
                lines[0].strip(),
                re.IGNORECASE,
            )
            if header:
                version, generated_at = header.groups()

        layer_z: list[float] = []
        layer_count = 0
        estimated_seconds = 0
        filament_length = 0.0
        filament_volume = 0.0
        filament_mass = 0.0
        features: Counter[str] = Counter()
        commands: Counter[str] = Counter()
        nozzle_temperatures: list[float] = []
        bed_temperatures: list[float] = []
        tools: set[int] = set()
        forbidden: set[str] = set()
        coordinates: dict[str, list[float]] = {axis: [] for axis in "XYZ"}
        current = {axis: 0.0 for axis in "XYZ"}
        absolute_xyz = True
        saw_g90 = False
        units_mm = False
        extrusion_mode: str | None = None
        embedded: dict[str, str] = {}

        for raw_line in lines:
            stripped = raw_line.strip()
            lower = stripped.lower()
            if stripped == ";LAYER_CHANGE":
                layer_count += 1
            elif stripped.startswith(";Z:"):
                try:
                    layer_z.append(float(stripped[3:]))
                except ValueError:
                    pass
            elif stripped.startswith(";TYPE:"):
                features[stripped[6:].strip()] += 1
            elif lower.startswith("; estimated printing time"):
                if match := _TIME.search(stripped):
                    estimated_seconds = _seconds(match)
            elif match := _FILAMENT.search(stripped):
                if match.group(1).lower() == "mm":
                    filament_length = float(match.group(2))
                else:
                    filament_volume = float(match.group(2))
            elif match := _FILAMENT_G.search(stripped):
                filament_mass = float(match.group(1))
            elif stripped.startswith(";") and " = " in stripped:
                key, value = stripped[1:].split(" = ", 1)
                embedded[key.strip()] = value.strip()

            code = stripped.split(";", 1)[0].strip()
            if not code:
                continue
            tokens = code.split()
            command_match = _COMMAND.fullmatch(tokens[0])
            if not command_match:
                if tool := re.fullmatch(r"T(\d+)", tokens[0], re.IGNORECASE):
                    tools.add(int(tool.group(1)))
                continue
            command = command_match.group(1).upper() + command_match.group(2)
            if command.endswith(".0"):
                command = command[:-2]
            commands[command] += 1
            if command.startswith("T"):
                tools.add(int(float(command[1:])))
            if command in FORBIDDEN_COMMANDS:
                forbidden.add(command)
            if command == "G20":
                units_mm = False
            elif command == "G21":
                units_mm = True
            elif command == "G90":
                absolute_xyz = True
                saw_g90 = True
            elif command == "G91":
                absolute_xyz = False
            elif command == "M82":
                extrusion_mode = "absolute"
            elif command == "M83":
                extrusion_mode = "relative"

            arguments: dict[str, float] = {}
            for token in tokens[1:]:
                match = _TOKEN.fullmatch(token)
                if match:
                    arguments[match.group(1).upper()] = float(match.group(2))
            if command in {"M104", "M109"} and "S" in arguments:
                nozzle_temperatures.append(arguments["S"])
            if command in {"M140", "M190"} and "S" in arguments:
                bed_temperatures.append(arguments["S"])
            if command == "G92":
                for axis in "XYZ":
                    if axis in arguments:
                        current[axis] = arguments[axis]
            elif command in {"G0", "G1", "G2", "G3"}:
                for axis in "XYZ":
                    if axis in arguments:
                        current[axis] = (
                            arguments[axis]
                            if absolute_xyz
                            else current[axis] + arguments[axis]
                        )
                        coordinates[axis].append(current[axis])

        bounds: dict[str, float] = {}
        for axis, values in coordinates.items():
            bounds[f"min_{axis.lower()}"] = round(min(values, default=0.0), 5)
            bounds[f"max_{axis.lower()}"] = round(max(values, default=0.0), 5)
        return cls(
            path=path,
            slicer_version=version,
            generated_at=generated_at,
            layer_count=layer_count,
            layer_z_min_mm=round(min(layer_z, default=0.0), 5),
            layer_z_max_mm=round(max(layer_z, default=0.0), 5),
            estimated_seconds=estimated_seconds,
            filament_length_mm=filament_length,
            filament_volume_cm3=filament_volume,
            filament_mass_g=filament_mass,
            motion_bounds_mm=bounds,
            nozzle_temperatures_c=tuple(nozzle_temperatures),
            bed_temperatures_c=tuple(bed_temperatures),
            units_mm=units_mm,
            absolute_xyz=saw_g90,
            extrusion_mode=extrusion_mode,
            tools=tuple(sorted(tools)),
            feature_counts=dict(sorted(features.items())),
            command_counts=dict(sorted(commands.items())),
            forbidden_commands=tuple(sorted(forbidden)),
            embedded_config=embedded,
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "path": self.path.name,
            "size_bytes": self.path.stat().st_size,
            "checksum_sha256": _sha256(self.path),
            "slicer_version": self.slicer_version,
            "generated_at": self.generated_at,
            "layer_count": self.layer_count,
            "layer_z_min_mm": self.layer_z_min_mm,
            "layer_z_max_mm": self.layer_z_max_mm,
            "estimated_seconds": self.estimated_seconds,
            "filament_length_mm": self.filament_length_mm,
            "filament_volume_cm3": self.filament_volume_cm3,
            "filament_mass_g": self.filament_mass_g,
            "motion_bounds_mm": dict(self.motion_bounds_mm),
            "temperatures_c": {
                "nozzle": list(self.nozzle_temperatures_c),
                "bed": list(self.bed_temperatures_c),
            },
            "units_mm": self.units_mm,
            "absolute_xyz": self.absolute_xyz,
            "extrusion_mode": self.extrusion_mode,
            "tools": list(self.tools),
            "feature_counts": dict(self.feature_counts),
            "command_counts": dict(self.command_counts),
            "forbidden_commands": list(self.forbidden_commands),
            "embedded_config": dict(self.embedded_config),
        }


@dataclass(frozen=True)
class GCodePreflightReport:
    passed: bool
    checks: tuple[dict[str, Any], ...]
    errors: tuple[str, ...]
    warnings: tuple[str, ...]
    claim_boundary: str = (
        "Disconnected G-code syntax, bounds, temperatures, modes, tools, and command policy "
        "were checked. This is not authorization to upload or run the file on hardware."
    )

    @classmethod
    def evaluate(cls, summary: GCodeSummary, profiles: ProfileBundle) -> "GCodePreflightReport":
        printer = profiles.printer
        material = profiles.material
        process = profiles.process
        x_limit, y_limit, z_limit = printer.build_volume_mm
        nozzle_nonzero = [value for value in summary.nozzle_temperatures_c if value > 0]
        bed_nonzero = [value for value in summary.bed_temperatures_c if value > 0]
        nozzle_max = max(nozzle_nonzero, default=0.0)
        bed_max = max(bed_nonzero, default=0.0)
        support_features = sum(
            count for name, count in summary.feature_counts.items() if "support" in name.lower()
        )
        checks: list[dict[str, Any]] = []

        def add(check_id: str, passed: bool, measured: Any, requirement: str) -> None:
            checks.append(
                {
                    "check_id": check_id,
                    "passed": bool(passed),
                    "measured": measured,
                    "requirement": requirement,
                }
            )

        bounds = summary.motion_bounds_mm
        add("has_layers", summary.layer_count > 0, summary.layer_count, "> 0 layers")
        add("millimetre_units", summary.units_mm, summary.units_mm, "G21 millimetre units")
        add("absolute_xyz_mode", summary.absolute_xyz, summary.absolute_xyz, "G90 present")
        add(
            "extrusion_mode",
            summary.extrusion_mode in {"absolute", "relative"},
            summary.extrusion_mode,
            "M82 or M83 present",
        )
        add(
            "x_bounds",
            bounds["min_x"] >= 0 and bounds["max_x"] <= x_limit,
            [bounds["min_x"], bounds["max_x"]],
            f"0..{x_limit} mm",
        )
        add(
            "y_bounds",
            bounds["min_y"] >= 0 and bounds["max_y"] <= y_limit,
            [bounds["min_y"], bounds["max_y"]],
            f"0..{y_limit} mm",
        )
        add(
            "z_bounds",
            bounds["min_z"] >= 0 and bounds["max_z"] <= z_limit,
            [bounds["min_z"], bounds["max_z"]],
            f"0..{z_limit} mm",
        )
        add(
            "nozzle_temperature",
            bool(nozzle_nonzero)
            and material.allowed_nozzle_temperature_c[0]
            <= nozzle_max
            <= min(
                material.allowed_nozzle_temperature_c[1],
                printer.maximum_nozzle_temperature_c,
            ),
            nozzle_max,
            (
                f"{material.allowed_nozzle_temperature_c[0]}.."
                f"{min(material.allowed_nozzle_temperature_c[1], printer.maximum_nozzle_temperature_c)} C"
            ),
        )
        add(
            "bed_temperature",
            bool(bed_nonzero)
            and material.allowed_bed_temperature_c[0]
            <= bed_max
            <= min(material.allowed_bed_temperature_c[1], printer.maximum_bed_temperature_c),
            bed_max,
            (
                f"{material.allowed_bed_temperature_c[0]}.."
                f"{min(material.allowed_bed_temperature_c[1], printer.maximum_bed_temperature_c)} C"
            ),
        )
        add(
            "single_tool",
            not summary.tools or summary.tools == (0,),
            list(summary.tools),
            "no tool other than T0",
        )
        add(
            "forbidden_commands",
            not summary.forbidden_commands,
            list(summary.forbidden_commands),
            "no forbidden or intervention commands",
        )
        add(
            "support_policy",
            process.support_policy != "disabled" or support_features == 0,
            support_features,
            "no generated support features when support policy is disabled",
        )
        add(
            "profile_layer_height",
            summary.embedded_config.get("layer_height") == f"{process.layer_height_mm:g}",
            summary.embedded_config.get("layer_height"),
            f"{process.layer_height_mm:g} mm",
        )
        errors = tuple(item["check_id"] for item in checks if not item["passed"])
        warnings = tuple(
            item
            for item in (
                "G-code remains disconnected and analysis-only",
                "physical adhesion, extrusion, cooling, and dimensional accuracy are unmeasured",
            )
        )
        return cls(passed=not errors, checks=tuple(checks), errors=errors, warnings=warnings)

    def to_dict(self) -> dict[str, Any]:
        return {
            "passed": self.passed,
            "checks": list(self.checks),
            "errors": list(self.errors),
            "warnings": list(self.warnings),
            "claim_boundary": self.claim_boundary,
        }
