import { describe, expect, it } from 'vitest'

import { parseGCodeToolpath } from './toolpath'

const twoLayerGcode = `; generated by fixture
G21
G90
M83
;LAYER_CHANGE
;Z:0.20
G1 X0 Y0 Z0.20 F1200
;TYPE:External perimeter
G1 X10 Y0 E0.40
G1 X10 Y10 E0.40
G0 X0 Y10
;LAYER_CHANGE
;Z:0.40
G1 Z0.40
;TYPE:Infill
G1 X0 Y0 E0.30
G2 X5 Y5 I2.5 J0 E0.20
`

describe('parseGCodeToolpath', () => {
  it('preserves layers, extrusion, travel, features, and omitted arcs', () => {
    const parsed = parseGCodeToolpath(twoLayerGcode)

    expect(parsed.summary.layerCount).toBe(2)
    expect(parsed.summary.totalSegmentCount).toBe(4)
    expect(parsed.summary.extrusionSegmentCount).toBe(3)
    expect(parsed.summary.travelSegmentCount).toBe(1)
    expect(parsed.summary.unsupportedArcCount).toBe(1)
    expect(parsed.summary.featureCounts).toEqual({
      'External perimeter': 2,
      Infill: 1,
    })
    expect(parsed.layers[0].zMm).toBe(0.2)
    expect(parsed.layers[0].segments).toHaveLength(15)
    expect(parsed.layers[1].zMm).toBe(0.4)
    expect(parsed.summary.warnings.join(' ')).toContain('not structural')
    expect(parsed.summary.warnings.join(' ')).toContain('arc command')
  })

  it('uses extrusion Z changes when explicit layer comments are unavailable', () => {
    const parsed = parseGCodeToolpath(`G21
G90
M82
G92 E0
G1 X0 Y0 Z0.2
G1 X5 Y0 E0.2
G1 Z0.4
G1 X5 Y5 E0.4
`)

    expect(parsed.summary.layerCount).toBe(2)
    expect(parsed.layers.map((layer) => layer.zMm)).toEqual([0.2, 0.4])
    expect(parsed.summary.extrusionSegmentCount).toBe(2)
  })

  it('refuses toolpaths without a millimetre declaration', () => {
    expect(() => parseGCodeToolpath('G90\nM83\n;LAYER_CHANGE\nG1 X1 Y1 E1\n')).toThrow(
      'G21 millimetre units',
    )
    expect(() => parseGCodeToolpath('G20\n;LAYER_CHANGE\nG1 X1 Y1 E1\n')).toThrow(
      'Inch-unit G-code',
    )
  })
})
