import type { components } from './generated/interface-api'

type ApiSchemas = components['schemas']

export type Capabilities = ApiSchemas['CapabilitiesView']
export type ComparisonAreaSummary = ApiSchemas['ComparisonAreaSummaryView']
export type ComparisonChange = ApiSchemas['ComparisonChangeView']
export type ComparisonRevision = ApiSchemas['ComparisonRevisionView']
export type RevisionComparison = ApiSchemas['RevisionComparisonResponse']
export type Source = ApiSchemas['SourceView']
export type RevisionSummary = ApiSchemas['RevisionSummary']
export type RevisionListResponse = ApiSchemas['RevisionListResponse']
export type RevisionListWindow = ApiSchemas['RevisionListWindowView']
export type EventRecord = ApiSchemas['EventView']
export type Finding = ApiSchemas['FindingView']
export type Artifact = ApiSchemas['ArtifactView']
export type Stage = ApiSchemas['StageView']
export type PackageSummary = ApiSchemas['PackageView']
export type Inspection = ApiSchemas['InspectionView']
export type InspectionCheck = ApiSchemas['InspectionCheckView']
export type InspectionFeature = ApiSchemas['InspectionFeatureView']
export type InspectionProfile = ApiSchemas['InspectionProfileView']
export type InspectionReport = ApiSchemas['InspectionReportView']
export type RevisionDetail = ApiSchemas['RevisionDetailResponse']
export type IntakeResponse = ApiSchemas['IntakeResponse']
export type LocalCodexStatus = ApiSchemas['LocalCodexStatusResponse']
